### ISSUE TITLE
Module Loader should load earlier than init

### ISSUE THREAD

**Issue by earnjam** [bluehost/endurance-wp-module-loader#1]
Loading this module at `init` with no priority (defaults to 10) prevents other modules from using the `widgets_init` action hook, since`widgets_init` is essentially an `init` call with a priority of 1. 

We should either add a negative priority to the `init` hook register, or else switch to a hook earlier in the call stack. I would think `plugins_loaded` or `after_setup_theme` should both work in this case (and might be more preferable to get ahead of anything else that might be using `init`)

**Comment by 0aveRyan** [comment]
@earnjam Glad you found your blocker!

I'm wondering if this could be hooked even earlier, if we're going to move it 🤔I think the earliest possible hook would be `plugins_loaded` at a priority of 1 (right after Core loads embeds and widgets).

**Comment by earnjam** [comment]
Yeah, in the PR I did a quick test on `plugins_loaded`, but it didn't work. Need to dig into why. I think that would be the optimal location if it works. It worked fine with `after_setup_theme`. 

Other option is to just not use hook at all and automatically start the module loader when it's included with the composer autoload. Downside there is the inability to unhook it if needed.

**Comment by 0aveRyan** [comment]
Hmm ok. Did you try initializing your code inside that module with `add_action( 'after_theme_setup' )` while it was fired on `plugins_loaded`?

Yeah I agree it should fire on an action hook. Part of me was even wondering about the plugin writing a tiny mu-plugin to fire the loading action, similar to how it currently adds the cache files.

One benefit of that mu-plugin approach would be the potential for a really nice debug module, where we would be able to check `is_user_logged_in()` + some query param and prevent one/all plugins from ever being loaded, switching theme, etc. Could be a super helpful diagnostic tool for support or us at camp to quickly and safely debug a live production site without needing to _truly_ disable plugins or switch theme.

**Comment by wpscholar** [comment]
All of the modules are registered on the after_setup_theme hook. Loading modules before that means that they won’t load.

**Comment by earnjam** [comment]
Ah, ok I think there might be 2 options then:
1) We could register them on `plugins_loaded` and load them with the module loader on `after_setup_theme`.
2) We could register them without an action hook when they are included by the autoloader, then load them in the module loader on `plugins_loaded`
